### ISSUE TITLE
请教关于token的用法

### ISSUE THREAD

**Issue by taylortaurus** [xiong-it/xiong-it.github.io#2]
大佬，问一下。
站点配置文件中仓库带有token的写法有什么语法吗？
看到coding和github的写法不一样。

**Comment by xiong-it** [comment]
token是在两个平台申请的

**Comment by taylortaurus** [comment]
这个知道就是，我在gitee使用github的写法，貌似不行。

**Comment by xiong-it** [comment]
抱歉，问题过于模糊，具体可参考hexo分支的.travis.yml文件写法和博客中提到的travis-ci的配置方法。

**Comment by taylortaurus** [comment]
```
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: https://AndroidMichaelX:coding_token@git.coding.net/AndroidMichaelX/AndroidMichaelX.git
  branch: master
- type: git
  repo: https://gh_token@github.com/xiong-it/xiong-it.github.io.git
  branch: master
```

上述两个repo后仓库的链接的写法，具体可以在哪里有文档参考。
部署到gitee，我写成这样`https://gitee_token@gitee.com/taylortaurus/taylortaurus.git`这样的写法，貌似不行。但是coding和github按照你给出的都可以。
